export const DRAWINGS = [
  { fileName: "milesburn1.jpg", title: "Milesburn Cabin", year: 2020, id: 1 },
  { fileName: "laurel_lake.JPG", title: "Laurel Lake", year: 2019, id: 2 },
  { fileName: "mountain_lake.jpg", title: "Mountain Lake", year: 2021, id: 3 },
  { fileName: "wave_chair.jpg", title: "Wave Chair", year: 2015, id: 4 },
  { fileName: "red_valley.jpg", title: "Red Valley", year: 2017, id: 5 },
  { fileName: "glenwood.jpg", title: "Glenwood Canyon", year: 2020, id: 6 },
  { fileName: "slate_canyon.jpg", title: "Slate Canyon", year: 2020, id: 7 },
  {
    fileName: "slate_canyon_2.jpg",
    title: "Slate Canyon 2",
    year: 2020,
    id: 8,
  },
  {
    fileName: "slate_canyon_3.jpg",
    title: "Slate Canyon 3",
    year: 2020,
    id: 9,
  },
  { fileName: "grave_ridge.jpg", title: "Grave Ridge", year: 2019, id: 10 },
  { fileName: "vic_vill_1.jpg", title: "Moon Cottage", year: 2020, id: 11 },
  { fileName: "jazz-night.JPG", title: "Jazz Night", year: 2021, id: 12 },
  {
    fileName: "work_for_what_we_have.JPG",
    title: "We Work For What We Have",
    year: 2019,
    id: 13,
  },
  {
    fileName: "color_wasatch_view.JPG",
    title: "Color Wasatch View",
    year: 2020,
    id: 14,
  },
  {
    fileName: "powerline_vista.JPG",
    title: "Powerline Vista",
    year: 2021,
    id: 15,
  },
  {
    fileName: "quehanna_hollow.JPG",
    title: "Hollow above Little Medix Run",
    year: 2022,
    id: 16,
  },
  {
    fileName: "trail_to_leconte.JPG",
    title: "View from Trail to Mt. LeConte",
    year: 2022,
    id: 17,
  },
  {
    fileName: "ridge_from_leconte.JPG",
    title: "Ridge viewed from trail to Mt. LeConte",
    year: 2022,
    id: 18,
  },
  {
    fileName: "camp_atop_leconte.JPG",
    title: "The Camp Atop Mt. LeConte",
    year: 2022,
    id: 19,
  },
  {
    fileName: "snowpine.jpg",
    title: "View from Snowpine Lodge of Mt. Baldy",
    year: 2022,
    id: 20,
  },
];
